version: '3.1'
services:
  front:
    build: .
    # env_file: ./.env
    networks:
      - frontend
    ports:
      - '3000:3000'

  nginx:
    build: ./nginx
    networks:
      - frontend
    depends_on:
      - front
    ports:
      - 8081:8080
networks:
  frontend:
    driver: bridge

  